main: intelli.worldchanges.WorldChanges
name: WorldChanges
version: 0.1a
author: Intelli
api-version: 1.16
description: Changes world every 5 mins

commands:
  wc:
    description: Start/Stop
